name: flutterings
description: "flutterings by IT B"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # GAME ENGINE
  flame: ^1.32.0

  # BACKEND
  supabase_flutter: ^2.10.2

  # STATE MANAGEMENT
  flutter_riverpod: ^3.0.1

  # UI / VISUALS
  google_fonts: ^6.3.2
  confetti: ^0.7.0
  cached_network_image: ^3.2.3

  # AUDIO
  just_audio: ^0.9.34
  audio_session: ^0.1.24

  # VIDEO
  video_player: ^2.6.1

  sensors_plus: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/character sprites/
    - assets/images/background/
    - assets/enemies/
    - assets/weapons/
    - assets/weapons/projectiles/
